import type { Metadata } from 'next';
import { Ubuntu } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/components/auth-context';
import { Toaster } from '@/components/ui/sonner';

const ubuntu = Ubuntu({
  variable: '--font-ubuntu',
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'The Undercommons',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${ubuntu.variable} antialiased`}>
        <AuthProvider>
          {children}
          <Toaster richColors />
        </AuthProvider>
      </body>
    </html>
  );
}
